### ISSUE TITLE
Pyparsing 2.4.0 update

### ISSUE THREAD

**Issue by calebj** [borntyping/python-dice#23]
Pyparsing 2.4.0 broke some stuff, and it's probably a good time to go through and modernize the codebase based on it so we can keep up. See pyparsing/pyparsing#85 for the example that brought it to my attention (h/t @Harmon758).

Here's my initial idea list, which I'll probably add to over time:
- properly use the `ParseResults` class returned as the tokens
- use the builtin `infixNotation` facilities instead of the custom `operatorPrecedence`
  - needs workaround for special-casing operands like in `dF` and `d%`

In the meantime, v2.4.1 of this library has a dependency on pyparsing>=2.0.1,<2.4.0.

**Comment by ptmcg** [comment]
You might consider dropping your disabling of `_trim_arity` also. Since version 2.1.8 (Aug, 2016), `_trim_arity` should be much smarter about distinguishing TypeErrors of its own making vs. those raised in user parse actions, handling its own errors, and reraising those from the parse action. If this is not what you are experiencing, please post an issue with example on the pyparsing repo.

To your question about all the extra `FollowedBy` expressions in `infixNotation`, these are there for two reasons: 1) avoid adding extra grouping for every level of precedence even if there is no operation present for the current level (just recursing to next level down), and 2) avoid multiple invocation of parse actions at the same level. With packrat enabled, the repeated calls to parse should have little impact on performance, since the actual parsing will be skipped and the results or exceptions will be obtained from the packrat cache. I do note that your precedence table is one of the largest I've ever seen, and may benefit from some partitioning.

Meanwhile, I'm currently looking at your grammar.py code to see how best to reproduce your infinite recursion issue, or possibly identify a lurking left-recursion in your expression.

**Comment by borntyping** [comment]
This sounds really good - most of this was written quite a long time ago, and I think it's definitely worth changing it to do things properly if possible. I wasn't expecting the code to still be around five years later!
